In [1]:
import pandas as pd
import numpy as np
import webbrowser
import os
from geopy.geocoders import ArcGIS
import time
import folium
import osmnx as ox
import networkx as nx
import pyproj
from shapely.geometry import Point

In [3]:
patient=pd.read_excel("patient_list.xlsx")
patient

       Patient Name  Age                                       Disease
0     Eleanor Vance   34                            Migraine with Aura
1       Marcus Chen   52                               Type 2 Diabetes
2   Aaliyah Jackson   28                                        Asthma
3     Liam O'Connor   67                                  Hypertension
4   Sophia Martinez   11                            Acute Otitis Media
5         David Kim   45                                          GERD
6       Emma Watson   73                                Osteoarthritis
7      Julius Novak   23                      Infectious Mononucleosis
8      Chloe Dubois   29                  Generalized Anxiety Disorder
9       Arjun Mehta   61              Chronic Kidney Disease (Stage 2)
10    Elena Rostova   38                                Hypothyroidism
11    Omar Al-Fayed   50                                Hyperlipidemia
12    Beatriz Silva   16                                 Acne Vulgaris
13    Tariq Mansoor   42                        Lumbar Disc Herniation
14  Naomi Takahashi   31                        Iron Deficiency Anemia
15    Lucas Fischer   58                          Rheumatoid Arthritis
16      Zoe Jenkins    7                                    Chickenpox
17      Mateo Rossi   35                Irritable Bowel Syndrome (IBS)
18      Fatima Diop   48                                  Fibromyalgia
19    Oliver Hansen   64  Chronic Obstructive Pulmonary Disease (COPD)
20      Yuki Tanaka   22                             Allergic Rhinitis
21     Samuel Green   70            Benign Prostatic Hyperplasia (BPH)
22   Isabella Costa   19                              Anorexia Nervosa
23     Isaac Wright   55                                          Gout
24     Amara Okafor   33              Polycystic Ovary Syndrome (PCOS)
25   William Taylor   79             Alzheimer's Disease (Early Stage)
26    Mia Lindstrom   26                                Celiac Disease
27    Carlos Mendez   41                                     Psoriasis
28     Harper Vance    3                 Hand, Foot, and Mouth Disease
29    Xavier Dupont   53                                   Sleep Apnea

In [18]:
G = ox.graph_from_place(
    "Greater Mumbai, Maharashtra, India",
    network_type="drive"
)

nodes, _ = ox.graph_to_gdfs(G)

sample = nodes.sample(n=len(patient), random_state=42)

addresses = sample[['y','x']].rename(
    columns={'y':'Latitude','x':'Longitude'}
)

In [19]:
idx = np.random.randint(0, len(addresses), size=len(patient))

patient["Latitude"] = addresses.iloc[idx]["Latitude"].values
patient["Longitude"] = addresses.iloc[idx]["Longitude"].values

In [20]:
patient

,Patient Name,Age,Disease,Latitude,Longitude
0,Eleanor Vance,34,Migraine with Aura,19.143896,72.995997
1,Marcus Chen,52,Type 2 Diabetes,19.458188,72.819044
2,Aaliyah Jackson,28,Asthma,19.251862,72.870831
3,Liam O'Connor,67,Hypertension,19.181006,73.051889
4,Sophia Martinez,11,Acute Otitis Media,19.024750,73.018203
5,David Kim,45,GERD,19.254993,73.032868
6,Emma Watson,73,Osteoarthritis,18.884484,72.914845
7,Julius Novak,23,Infectious Mononucleosis,19.254993,73.032868
8,Chloe Dubois,29,Generalized Anxiety Disorder,19.251862,72.870831
9,Arjun Mehta,61,Chronic Kidney Disease (Stage 2),19.161230,72.786317
10,Elena Rostova,38,Hypothyroidism,19.453727,72.805569
11,Omar Al-Fayed,50,Hyperlipidemia,19.143896,72.995997
12,Beatriz Silva,16,Acne Vulgaris,19.142704,73.250039
13,Tariq Mansoor,42,Lumbar Disc Herniation,19.453727,72.805569
14,Naomi Takahashi,31,Iron Deficiency Anemia,19.027047,73.018063
15,Lucas Fischer,58,Rheumatoid Arthritis,19.021010,72.837567
16,Zoe Jenkins,7,Chickenpox,18.930216,73.381848
17,Mateo Rossi,35,Irritable Bowel Syndrome (IBS),18.988236,73.133013
18,Fatima Diop,48,Fibromyalgia,19.159614,73.237598
19,Oliver Hansen,64,Chronic Obstructive Pulmonary Disease (COPD),18.930216,73.381848
20,Yuki Tanaka,22,Allergic Rhinitis,19.232382,72.844193
21,Samuel Green,70,Benign Prostatic Hyperplasia (BPH),19.027047,73.018063
22,Isabella Costa,19,Anorexia Nervosa,18.988236,73.133013
23,Isaac Wright,55,Gout,19.161230,72.786317
24,Amara Okafor,33,Polycystic Ovary Syndrome (PCOS),19.161230,72.786317
25,William Taylor,79,Alzheimer's Disease (Early Stage),19.453727,72.805569
26,Mia Lindstrom,26,Celiac Disease,19.073272,73.010227
27,Carlos Mendez,41,Psoriasis,19.453727,72.805569
28,Harper Vance,3,"Hand, Foot, and Mouth Disease",19.021010,72.837567
29,Xavier Dupont,53,Sleep Apnea,19.251862,72.870831

In [65]:
def create_map(df,graph,graph_proj):
    tiles ="https://{s}.basemaps.cartocdn.com/rastertiles/voyager_nolabels/{z}/{x}/{y}{r}.png"
    latitude=(df['Latitude'].max()+df['Latitude'].min())/2
    longitude=(df['Longitude'].max()+df['Longitude'].min())/2

    m = folium.Map(
         location=[latitude,longitude],
         zoom_start=10,
         tiles=tiles,
         attr='© OpenStreetMap © CARTO'
    )
    grouped = df.groupby(["Latitude", "Longitude"])
    count_df=grouped.size().reset_index(name="Count")
    count_lookup = count_df.set_index(["Latitude", "Longitude"])["Count"]

    min_value = count_df["Count"].min()
    max_value = count_df["Count"].max()
    for (lat, lon), group in grouped:
       count = count_lookup.loc[(lat, lon)]

       if max_value == min_value:
          opacity = 0.8
       else:
        opacity = (count - min_value) / (max_value - min_value)
       popup = "<br>".join(
        f"{row['Patient Name']} ({row['Age']} yrs, {row['Disease']})"
        for _, row in group.iterrows()
    )
       folium.CircleMarker(
        location=[lat, lon],
        radius=8+len(group),
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity= 1-opacity * 0.7,
        popup=folium.Popup(popup, max_width=350)
    ).add_to(m)
       folium.Marker(
    location=[lat,lon],
    icon=folium.DivIcon(
        icon_size=(60, 30),
        icon_anchor=(-10, 5),
        html=f"""
        <div style="
            font-size:10px;
            font-weight:bold;
            color:black;
            background-color:white;
            border:1px solid black;
            border-radius:4px;
            padding:1px 4px;
            white-space: nowrap;
        ">
        {len(group)} patient(s)
        </div>
        """
    )
).add_to(m)

    file_name = "patient_mapping.html"
    m.save(file_name)  

    # Open the generated map in the default web browser             
    webbrowser.open('file://' + os.path.realpath(file_name))

In [66]:
padding = 0.03                                                 

    # Determine geographic bounding box limits
north =patient["Latitude"].max() + padding
south =patient["Latitude"].min() - padding
east =patient["Longitude"].max() + padding
west =patient["Longitude"].min() - padding 
    
    # Download drivable road network within the bounding box
graph = ox.graph_from_bbox(bbox=(west, south, east, north), network_type="drive")

    # Verify that a valid road network was retrieved
if len(graph) == 0:
        raise ValueError("No drivable roads found in this specific coordinate region.")
    
    # Project graph to a suitable coordinate reference system for accurate distance calculations
graph_proj = ox.project_graph(graph)
create_map(patient,graph,graph_proj)